services:

  # Source: https://abhishektatachar.medium.com/run-chroma-db-on-a-local-machine-and-as-a-docker-container-a9d4b91d2a97
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - ../chroma_db:/chroma/.chroma/index
    ports:
      - 8000:8000
  
  api:
    image: gospel-search-api
    build:
      context: ..
      dockerfile: dockerfiles/api.Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      - chroma
    ports:
    - 3000:3000
    environment:
      CHROMA_HOST: chroma
      CHROMA_PORT: 8000
      OPENAI_API_KEY: ${OPENAI_API_KEY}

  worker:
    image: gospel-search-worker
    build:
      context: ..
      dockerfile: dockerfiles/worker.Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      - chroma
    ports:
    - 8080:8080
    volumes:
    - ~/.cache/torch:/root/.cache/torch
    environment:
      DB_USERNAME: root
      DB_PASSWORD: password
      CHROMA_HOST: chroma
      CHROMA_PORT: 8000
