services:

  mongodb:
    image: mongo
    volumes:
      - ../db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  mongoui:
    image: mongo-express
    ports:
    - 8081:8081
    depends_on:
    - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb

  elasticsearch:
    image: elasticsearch:7.17.3
    environment:
      discovery.type: single-node
  
  nlp-service:
    image: gospel-search-nlp-service
    build:
      context: ..
      dockerfile: dockerfiles/nlp-service.Dockerfile
    volumes:
    - ~/.cache/torch:/root/.cache/torch
    environment:
      DB_HOST: mongodb
      DB_USERNAME: root
      DB_PASSWORD: password

  # TODO: just define a single worker service and call it using different commands,
  # instead of having these duplicate definitions.

  crawler:
    image: gospel-search-crawler
    build:
      context: ..
      dockerfile: dockerfiles/crawler.Dockerfile
    environment:
      DB_HOST: mongodb
      DB_USERNAME: root
      DB_PASSWORD: password
    command: ["python", "-m", "gospel_search.mongodb.pull_pages", "--limit", "4"]

  extractor:
    image: gospel-search-crawler
    build:
      context: ..
      dockerfile: dockerfiles/crawler.Dockerfile
    environment:
      DB_HOST: mongodb
      DB_USERNAME: root
      DB_PASSWORD: password
    command: ["python", "-m", "gospel_search.mongodb.extract_segments"]

  embedder:
    image: gospel-search-embedder
    build:
      context: ..
      dockerfile: dockerfiles/embedder.Dockerfile
    volumes:
    - ~/.cache/torch:/root/.cache/torch
    environment:
      DB_HOST: mongodb
      DB_USERNAME: root
      DB_PASSWORD: password
    command: ["python", "-m", "gospel_search.mongodb.compute_embeddings"]

  importer:
    image: gospel-search-crawler
    build:
      context: ..
      dockerfile: dockerfiles/crawler.Dockerfile
    environment:
      DB_HOST: mongodb
      DB_USERNAME: root
      DB_PASSWORD: password
      ES_HOST: http://elasticsearch:9200
    command: ["python", "-m", "gospel_search.elasticsearch.import_segments"]
