services:

  mongodb:
    image: mongo
    volumes:
      - ../db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  mongoui:
    image: mongo-express
    ports:
    - 8081:8081
    depends_on:
    - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb

  # Source: https://abhishektatachar.medium.com/run-chroma-db-on-a-local-machine-and-as-a-docker-container-a9d4b91d2a97
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - ../chroma_db:/chroma/.chroma/index
    ports:
      - 8000:8000
  
  proxy-service:
    image: gospel-search-proxy-service
    build:
      context: ..
      dockerfile: dockerfiles/proxy-service.Dockerfile
    depends_on:
      - chroma
    ports:
    - 3000:3000
    environment:
      CHROMA_HOST: chroma
      CHROMA_PORT: 8000
      OPENAI_API_KEY: ${OPENAI_API_KEY}

  worker:
    image: gospel-search-worker
    build:
      context: ..
      dockerfile: dockerfiles/worker.Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      - mongodb
      - chroma
    ports:
    - 8080:8080
    volumes:
    - ~/.cache/torch:/root/.cache/torch
    environment:
      DB_HOST: mongodb
      DB_USERNAME: root
      DB_PASSWORD: password
      CHROMA_HOST: chroma
      CHROMA_PORT: 8000
