services:

  mongodb:
    image: mongo
    volumes:
      - ../db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  mongoui:
    image: mongo-express
    ports:
    - 8081:8081
    depends_on:
    - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb

  elasticsearch:
    image: elasticsearch:7.17.18
    volumes:
      - ../es-db:/var/lib/elasticsearch/data
    environment:
      discovery.type: single-node
      http.cors.enabled: "true"
      http.cors.allow-origin: http://elasticsearchui:1358
      http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      http.cors.allow-credentials: "true"
    ports:
    - 9200:9200
  
  elasticsearchui:
    image: appbaseio/dejavu:3.6.0
    ports:
    - 1358:1358
    depends_on:
      - elasticsearch
  
  nlp-service:
    image: gospel-search-nlp-service
    build:
      context: ..
      dockerfile: dockerfiles/nlp-service.Dockerfile
    depends_on:
    - mongodb
    volumes:
    - ~/.cache/torch:/root/.cache/torch
    environment:
      DB_HOST: mongodb
      DB_USERNAME: root
      DB_PASSWORD: password
  
  proxy-service:
    image: gospel-search-proxy-service
    build:
      context: ..
      dockerfile: dockerfiles/proxy-service.Dockerfile
    depends_on:
      - elasticsearch
      - nlp-service
    ports:
    - 3000:3000
    environment:
      ES_HOST: http://elasticsearch:9200
      NLP_HOST: http://nlp-service:8080

  worker:
    image: gospel-search-worker
    build:
      context: ..
      dockerfile: dockerfiles/worker.Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      - mongodb
      - elasticsearch
    ports:
    - 8080:8080
    volumes:
    - ~/.cache/torch:/root/.cache/torch
    environment:
      DB_HOST: mongodb
      DB_USERNAME: root
      DB_PASSWORD: password
      ES_HOST: http://elasticsearch:9200
